Migrate new PHPUnit config and update ignored file
raml-org/raml-php-parser pull request #171
Opened 2021-03-07 18:41 UTC by peter279k

# Changed log

- Adding the `.phpunit.result.cache` on `.gitignore` file to let this file remove from Git version control because this is a cached result file generated by `PHPUnit 9.x` version.
- Using the `./bin/phpunit --migrate-configuration --configuration=./tools/phpunit/config.xml` command to migrate PHPUnit configuration file because of following message:

```
Warning:       Your XML configuration validates against a deprecated schema.
Suggestion:    Migrate your XML configuration using "--migrate-configuration"!
```

2021-03-07 18:48 UTC, martin-georgiev requested changes

2021-03-07 18:48 UTC, martin-georgiev commented on .gitignore
> +.phpunit.result.cache
Ideally, this will be part of the developer's global git ignore configuration and won't be pushed to a public repository.

2021-03-07 18:49 UTC, peter279k commented on .gitignore
> +.phpunit.result.cache
Reveted.

2021-03-07 18:54 UTC, martin-georgiev commented
CI is failing due to Fabien's security checker changes from last month. We will need a new PR that addresses the security-checker migration to unblock this PR. @peter279k, would you be able to open a new PR with changes similar to [these](https://github.com/martin-georgiev/postgresql-for-doctrine/pull/83/files), please?

2021-03-07 18:55 UTC, martin-georgiev commented on .gitignore
> +.phpunit.result.cache
Thank you.

2021-03-07 18:58 UTC, martin-georgiev commented on tools/phpunit/config.xml
> - >
When the attributes' order and the spread across multiple lines is preserved, it will be easier to review and identify what exactly is changing. This helps current and future reviewers to better understand the exact scope of changes.

2021-03-07 19:00 UTC, martin-georgiev commented on tools/phpunit/config.xml
> +  </testsuites>
The indentation changed from 4 to 2 spaces but this doesn't seem to bring value. It adds noise to the diff and makes it harder to spot real changes. Can you please preserve the original indentation?

2021-03-07 19:50 UTC, martin-georgiev commented on composer.json
> +    "sensiolabs-de/deptrac-shim": "^0.10",
I'm not sure how this made it here. This repo doesn't have a setup for `deptrac`. Further to that, `sensiolabs-de` does not exist anymore. Their copyright agreement expired some months ago.

2021-03-07 19:53 UTC, martin-georgiev commented on composer.json
> +      "local-php-security-checker"
As already requested [here](https://github.com/raml-org/raml-php-parser/pull/171#issuecomment-792332846), can you please extract any `security-checker` related changes in a separate PR. Ideally, each PR will contain only atomic changes for a single migration and won't mix PHPUnit with security-checker for example.

2021-03-08 06:07 UTC, peter279k commented
Hi @martin-georgiev, thanks for your reply.

The PR #173 has been created. Once the PR #173 has been merged, I will go back to work on this :).

2021-03-08 10:21 UTC, peter279k commented
Move to PR #174.

2021-03-08 10:21 UTC, closed without merging